[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# PROXY a Render (debe ir ANTES del catch-all SPA)
[[redirects]]
  from = "/api/*"
  to = "https://klevergold-epitome.onrender.com/:splat"
  status = 200
  force = true

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true
