# netlify.toml — configura el directorio de funciones y CORS
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# CORS para funciones
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "OPTIONS, POST, GET"
