# render.yaml — Despliegue automático del backend EPITOME (FastAPI) en Render
services:
  - type: web
    name: klevergold-epitome
    env: python
    rootDirectory: epitome-backend
    buildCommand: pip install -U pip && pip install -e .
    startCommand: uvicorn epitome.api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: EPITOME_ALLOWED_ORIGINS
        value: "*"
      - key: EPITOME_COVERAGE_TARGET
        value: "0.90"
